# Generated by Django 4.1.6 on 2023-02-06 19:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=4)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geom_m', django.contrib.gis.db.models.fields.PointField(srid=26911)),
            ],
        ),
    ]
