# Generated by Django 4.1.6 on 2023-02-08 11:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_lat_alter_shop_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZIP', models.CharField(max_length=6)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=26911)),
            ],
        ),
    ]
