# Generated by Django 4.1.6 on 2023-02-12 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_shop_aluminum_body_shop_aluminum_structure_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="name",
            new_name="business_name",
        ),
    ]
