# Generated by Django 4.1.6 on 2023-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0006_shop_luxury_structural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcodes",
            name="ZIP",
            field=models.CharField(max_length=10),
        ),
    ]
